import Link from "next/link";
import PaperSearch from "@/components/PaperSearch";
import { availableYears, getSubject, mediumNames, paperPath, papers, searchIndex, subjectGroups, subjects } from "@/data/papers";

export default function Home(){
 const paperCount=papers.filter(p=>p.paperUrl).length,answerCount=papers.filter(p=>p.markingSchemeUrl).length,completeCount=papers.filter(p=>p.paperUrl&&p.markingSchemeUrl).length;
 const latest=[...papers].sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)).slice(0,8);
 return <>
  <section className="hero"><div className="dots"/><div className="shell heroGrid"><div className="heroCopy"><div className="eyebrow"><i/>O/L සිසුන් වෙනුවෙන්ම</div><h1>ඔබේ O/L <em>A</em> එක<br/>නිවැරදි <span>paper</span> එකෙන්.</h1><p>නිල O/L පසුගිය ප්‍රශ්න පත්‍ර, marking schemes සහ answers—විෂය, වසර හා මාධ්‍ය අනුව, සම්පූර්ණයෙන්ම නොමිලේ.</p><div className="heroButtons"><Link className="primary" href="#search">⌕ පේපර් එක සොයන්න</Link><Link className="plain" href="#subjects">විෂයන් බලන්න →</Link></div><div className="trust"><span>සි</span><span>த</span><span>EN</span><p><b>Account අවශ්‍ය නැහැ</b><br/>Direct access · සැමදා නොමිලේ</p></div></div><div className="finder"><div className="finderTop"><span>01</span><h2>ඔබ සොයන විෂය කුමක්ද?</h2></div><div className="quickSubjects">{subjects.slice(0,4).map((s,i)=><Link href={`/ol/${s.slug}/`} key={s.slug}><i className={s.color}>{s.mark}</i><b>{s.si}</b><small>{s.en}</small>{i===0&&<em>POPULAR</em>}</Link>)}</div><div className="free">✓ නිල papers · Marking schemes · Free access</div></div></div></section>
  <section className="homeStats"><div className="shell statStrip"><div><strong>{paperCount}</strong><span>Official Papers</span></div><div><strong>{answerCount}</strong><span>Official Answers</span></div><div><strong>{completeCount}</strong><span>Complete Sets</span></div><div><strong>{subjects.length}</strong><span>Subject Options</span></div></div></section>
  <section className="shell intro" id="subjects"><div className="sectionTitle"><div><small>විෂය තෝරන්න</small><h2>O/L විෂය කාණ්ඩ</h2><p>අනිවාර්ය විෂයයන් සහ ඔබ තෝරාගත් කාණ්ඩ විෂයයන් අනුව papers සොයන්න.</p></div></div>{subjectGroups.map(group=><section className="subjectGroup" key={group.id}><div className="groupHeading"><div><span>{group.id==="core"?"06":group.id==="group-1"?"I":group.id==="group-2"?"II":"III"}</span><div><h3>{group.title}</h3><p>{group.description}</p></div></div></div><div className="subjectGrid">{subjects.filter(s=>s.group===group.id).map(s=><Link className={`subjectCard ${s.color}`} href={`/ol/${s.slug}/`} key={s.slug}><i>{s.mark}</i><div><h3>{s.si}</h3><p>{s.en}</p><span>{papers.filter(p=>p.subject===s.slug).length} resources →</span></div></Link>)}</div></section>)}</section>
  <section className="latestSection"><div className="shell"><div className="sectionTitle"><div><small>RECENTLY VERIFIED</small><h2>අලුතින් update කළ resources</h2><p>Department of Examinations නිල links අනුව නවතම papers සහ answers.</p></div></div><div className="latestGrid">{latest.map(p=>{const s=getSubject(p.subject);return <Link href={paperPath(p)} key={p.id}><span className="pdf">PDF</span><div><b>{p.displayYear} O/L {s?.si}</b><small>{mediumNames[p.medium]} · {p.paperUrl&&p.markingSchemeUrl?"Paper + Answers":p.paperUrl?"Question Paper":"Official Answers"}</small></div><i>→</i></Link>})}</div><div className="yearChips"><b>වසර අනුව:</b>{availableYears.map(year=><Link href={`/ol-past-papers/${year}/`} key={year}>{year}</Link>)}</div></div></section>
  <section className="paperSection" id="papers"><div className="shell"><div className="sectionTitle"><div><small>O/L PAPER FINDER</small><h2>ඔබට අවශ්‍ය paper එක සොයන්න</h2><p>විෂය, වසර හෝ මාධ්‍ය අනුව filter කරන්න.</p></div></div><PaperSearch papers={searchIndex(papers)}/></div></section>
  <section className="tools"><div className="shell toolGrid"><div><small>PDF වලට වඩා වැඩි යමක්</small><h2>හරි විදිහට<br/>practice කරමු.</h2><p>Paper එකක් කරන සෑම වාරයක්ම ඔබේ result එකට ගෙනයන පියවරක් කරගන්න.</p></div><div className="miniTools"><article><span>◷</span><b>විභාග Timer</b><strong>02:59:41</strong><i><b/></i><p>නියමිත වේලාවට paper එක practice කරන්න.</p></article><article><span>✓</span><b>Progress tracker</b><div className="days"><i>✓</i><i>✓</i><i>✓</i><i>Th</i><i>F</i></div><p><strong>පේපර් 3ක්</strong> මේ සතියේ අවසන්.</p></article></div></div></section>
  <section className="guides shell" id="guides"><div className="sectionTitle"><div><small>O/L STUDY GUIDES</small><h2>පුංචි tips. ලොකු ප්‍රතිඵල.</h2></div><Link className="plain" href="/guides/">සියලු guides →</Link></div><div className="guideGrid"><Link href="/guides/90-day-ol-revision-plan/"><div>90<small>DAYS</small></div><span>EXAM PLANNING · 6 MIN</span><h3>දින 90ක O/L revision plan එකක් හදන්නේ කොහොමද?</h3></Link><Link href="/guides/ol-mcq-mistakes/"><div>MCQ<small>✓ × ?</small></div><span>EXAM SKILLS · 4 MIN</span><h3>MCQ paper එකේ marks අහිමි කරන වැරදි 5ක්</h3></Link><Link href="/guides/three-pass-paper-method/"><div>3h<small>FOCUS</small></div><span>TIME MANAGEMENT · 5 MIN</span><h3>3-pass ක්‍රමයෙන් වෙලාවට paper එක අවසන් කරමු</h3></Link></div></section>
 </>
}
