"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {subjects} from "@/data/subject-meta";
export type SearchPaper={id:string;subject:string;subjectSi:string;year:number;displayYear:string;medium:"sinhala"|"english"|"tamil";hasPaper:boolean;hasAnswer:boolean;answerType?:"marking-scheme"|"evaluation-report"};
const mediumNames={sinhala:"සිංහල මාධ්‍ය",english:"English Medium",tamil:"தமிழ் மொழி"};
const path=(p:SearchPaper)=>`/ol/${p.subject}/${p.year}/${p.medium}/`;
const resourceLabel=(p:SearchPaper)=>p.hasPaper?"ප්‍රශ්න පත්‍රය":p.answerType==="evaluation-report"?"Evaluation Report / Answers":"Marking Scheme / Answers";
export default function PaperSearch({papers,initialType="all"}:{papers:SearchPaper[];initialType?:"all"|"papers"|"answers"|"complete"}){
 const [query,setQuery]=useState(""),[subject,setSubject]=useState("all"),[medium,setMedium]=useState("all"),[year,setYear]=useState("all"),[resourceType,setResourceType]=useState(initialType),[visible,setVisible]=useState(30);
 const years=[...new Set(papers.map(p=>p.year))].sort((a,b)=>b-a);
 const list=useMemo(()=>papers.filter(p=>{const s=subjects.find(x=>x.slug===p.subject),hay=`${p.subjectSi} ${s?.en} ${s?.si} O/L ${p.year} ${p.displayYear} ${p.medium}`.toLowerCase(),typeMatch=resourceType==="all"||resourceType==="papers"&&p.hasPaper||resourceType==="answers"&&p.hasAnswer||resourceType==="complete"&&p.hasPaper&&p.hasAnswer;return(!query||hay.includes(query.toLowerCase()))&&(subject==="all"||p.subject===subject)&&(medium==="all"||p.medium===medium)&&(year==="all"||p.year===Number(year))&&typeMatch}),[papers,query,subject,medium,year,resourceType]);
 useEffect(()=>setVisible(30),[query,subject,medium,year,resourceType]);
 return <section className="searchArea" id="search"><div className="searchBox"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="උදා: 2025 O/L ගණිතය Sinhala..." aria-label="Papers සොයන්න"/></div><div className="filters"><select value={subject} onChange={e=>setSubject(e.target.value)} aria-label="විෂය"><option value="all">සියලු විෂයන්</option>{subjects.map(s=><option key={s.slug} value={s.slug}>{s.si}</option>)}</select><select value={year} onChange={e=>setYear(e.target.value)} aria-label="වසර"><option value="all">සියලු වසර</option>{years.map(y=><option key={y} value={y}>{y}</option>)}</select><select value={medium} onChange={e=>setMedium(e.target.value)} aria-label="මාධ්‍ය"><option value="all">සියලු මාධ්‍ය</option><option value="sinhala">සිංහල</option><option value="english">English</option><option value="tamil">தமிழ்</option></select><select value={resourceType} onChange={e=>setResourceType(e.target.value as typeof resourceType)} aria-label="Resource වර්ගය"><option value="all">Papers සහ Answers</option><option value="complete">Paper + Answers</option><option value="papers">Question Papers</option><option value="answers">Answers පමණක්</option></select></div><div className="resultHead"><b>{list.length} resources හමුවුණා</b><span>{list.slice(0,visible).length}ක් පෙන්වයි · නිල links</span></div><div className="paperList">{list.slice(0,visible).map(p=>{const sub=subjects.find(s=>s.slug===p.subject);return <Link className="paperRow" href={path(p)} key={p.id}><span className="pdf">PDF</span><span className="paperName"><b>{p.displayYear} O/L {sub?.si} {resourceLabel(p)}</b><small>{sub?.en} · {mediumNames[p.medium]}</small></span><span className="year"><b>{p.displayYear}</b><small>විභාග වසර</small></span><span className={`answer ${p.hasPaper&&p.hasAnswer?"complete":p.hasAnswer?"answerOnly":"paperOnly"}`}>{p.hasPaper&&p.hasAnswer?"✓ COMPLETE":p.hasAnswer?"✓ ANSWERS":"PAPER"}</span><span className="go">→</span></Link>})}{list.length===0&&<div className="empty">ගැළපෙන resource එකක් නැහැ. වෙනත් වසරක්, විෂයක් හෝ filter එකක් තෝරන්න.</div>}</div>{visible<list.length&&<button className="showMore" onClick={()=>setVisible(v=>v+30)}>තවත් resources පෙන්වන්න · {list.length-visible} ඉතිරි</button>}</section>
}
