import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { answerLabel, getPaper, getSubject, mediumNames, paperPath, papers, resourceLabel } from "@/data/papers";
import { site } from "@/lib/site";

type Props={params:Promise<{subject:string;year:string;medium:string}>};
export function generateStaticParams(){return papers.map(p=>({subject:p.subject,year:String(p.year),medium:p.medium}))}
export async function generateMetadata({params}:Props):Promise<Metadata>{
 const x=await params,p=getPaper(x.subject,Number(x.year),x.medium),s=getSubject(x.subject);if(!p||!s)return{};
 const kind=p.paperUrl?"Past Paper":p.answerType==="evaluation-report"?"Evaluation Report":"Marking Scheme";const title=`${p.displayYear} O/L ${s.en} ${kind} – ${mediumNames[p.medium]}`;
 const description=p.paperUrl?(p.hasMarkingScheme?`Download the official ${p.displayYear} G.C.E. O/L ${s.en} past paper and answers in ${mediumNames[p.medium]}.`:`Download the official ${p.displayYear} G.C.E. O/L ${s.en} past paper in ${mediumNames[p.medium]}.`):`Download the official ${p.displayYear} G.C.E. O/L ${s.en} ${kind.toLowerCase()} with answers in ${mediumNames[p.medium]}.`;
 return {title,description,alternates:{canonical:paperPath(p)},openGraph:{title,description}};
}
export default async function PaperPage({params}:Props){
 const x=await params,p=getPaper(x.subject,Number(x.year),x.medium),s=getSubject(x.subject);if(!p||!s)notFound();
 const sameSubject=papers.filter(x=>x.subject===p.subject&&x.medium===p.medium).sort((a,b)=>b.year-a.year),position=sameSubject.findIndex(x=>x.id===p.id),newer=position>0?sameSubject[position-1]:null,older=position>=0&&position<sameSubject.length-1?sameSubject[position+1]:null;
 const media=papers.filter(x=>x.subject===p.subject&&x.year===p.year),related=papers.filter(x=>x.subject===p.subject&&x.id!==p.id).slice(0,5),sameYear=papers.filter(x=>x.year===p.year&&x.subject!==p.subject&&x.medium===p.medium).slice(0,6),base=site.url,kind=p.paperUrl?"Exam paper":p.answerType==="evaluation-report"?"Evaluation report":"Marking scheme";
 const schema={"@context":"https://schema.org","@type":"DigitalDocument",name:`${p.displayYear} O/L ${s.en} ${kind} – ${mediumNames[p.medium]}`,inLanguage:p.medium==="sinhala"?"si":p.medium==="tamil"?"ta":"en",educationalLevel:"G.C.E. Ordinary Level",learningResourceType:kind,dateModified:p.updatedAt,url:`${base}${paperPath(p)}`,publisher:{"@type":"Organization",name:"O/L Past Papers"},isBasedOn:p.sourceUrl};
 const crumbs={"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:base},{"@type":"ListItem",position:2,name:`O/L ${s.en}`,item:`${base}/ol/${s.slug}/`},{"@type":"ListItem",position:3,name:`${p.displayYear} ${mediumNames[p.medium]}`,item:`${base}${paperPath(p)}`}]};
 return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(crumbs)}}/>
 <section className="detailHero"><div className="shell"><nav className="crumbs"><Link href="/">මුල් පිටුව</Link><span>›</span><Link href={`/ol/${s.slug}/`}>{s.si}</Link><span>›</span><b>{p.displayYear}</b></nav><div className="verified">✓ OFFICIAL RESOURCE</div><h1>{p.displayYear} O/L {s.si}<br/>{resourceLabel(p)}</h1><p>{mediumNames[p.medium]} · G.C.E. Ordinary Level · {p.paperUrl&&p.hasMarkingScheme?"Paper + answers":p.paperUrl?"Question paper":"Official answers"}</p><div className="mediumSwitch"><span>මාධ්‍යය:</span>{(["sinhala","english","tamil"] as const).map(m=>{const option=media.find(x=>x.medium===m);return option?<Link className={m===p.medium?"active":""} href={paperPath(option)} key={m}>{mediumNames[m]}</Link>:<span className="disabledMedium" key={m}>{mediumNames[m]} —</span>})}</div></div></section>
 <section className="shell detailGrid"><article className="downloadCard"><div className="docVisual"><span>PDF</span><b>{s.mark}</b><small>{p.displayYear}</small></div><div><h2>Official PDF ලබාගන්න</h2><p>පහත links Department of Examinations නිල resource catalogue එකෙන් තහවුරු කර ඇත.</p>{p.paperUrl&&<a className="downloadBtn" href={p.paperUrl} target="_blank" rel="nofollow noreferrer">↓ Question paper download</a>}{p.markingSchemeUrl&&<a className={p.answerType==="evaluation-report"?"evalBtn":"schemeBtn"} href={p.markingSchemeUrl} target="_blank" rel="nofollow noreferrer">✓ {answerLabel(p)}</a>}{p.paperUrl&&!p.markingSchemeUrl&&<div className="missingAnswer">Official answer link එක දැනට ලබාගත නොහැක.</div>}<a className="source" href={p.sourceUrl} target="_blank" rel="noreferrer">Official source: {p.sourceName} ↗</a></div></article><aside className="facts"><h2>Resource details</h2><dl><div><dt>විභාගය</dt><dd>G.C.E. O/L</dd></div><div><dt>විෂය</dt><dd>{s.si}</dd></div><div><dt>වසර</dt><dd>{p.displayYear}</dd></div><div><dt>මාධ්‍ය</dt><dd>{mediumNames[p.medium]}</dd></div><div><dt>ලබාගත හැක</dt><dd>{p.paperUrl&&p.hasMarkingScheme?"Paper + answers":p.paperUrl?"Question paper":answerLabel(p)}</dd></div></dl></aside></section>
 <section className="shell articleCopy"><h2>{p.displayYear} O/L {s.en} {p.paperUrl?"Past Paper":answerLabel(p)}</h2><p>මෙම පිටුව {p.displayYear} අ.පො.ස. සාමාන්‍ය පෙළ {s.si} {p.paperUrl?"නිල ප්‍රශ්න පත්‍රය":`නිල ${answerLabel(p)}` } සඳහා සකස් කර ඇත. Download කිරීමට පෙර නිවැරදි වසර සහ මාධ්‍යය තෝරා ඇති බව තහවුරු කරගන්න.</p>{p.paperUrl&&<><h2>Paper එක භාවිත කරන ආකාරය</h2><ol><li>නියමිත විභාග කාලය තුළ සටහන් නොබලා paper එක කරන්න.</li><li>ලබාගත හැකි නම් marking scheme එකෙන් පිළිතුරු පරීක්ෂා කරන්න.</li><li>වැරදි පිළිතුරු වෙනම සටහන් කර නැවත පුහුණු වන්න.</li></ol></>}</section>
 {(older||newer)&&<nav className="yearNav shell">{older?<Link href={paperPath(older)}><span>← පෙර වසර</span><b>{older.displayYear} {s.si}</b></Link>:<span/>}{newer?<Link href={paperPath(newer)}><span>නව වසර →</span><b>{newer.displayYear} {s.si}</b></Link>:<span/>}</nav>}
 {related.length>0&&<section className="related shell"><h2>වෙනත් {s.si} papers සහ answers</h2><div className="relatedGrid">{related.map(r=><Link href={paperPath(r)} key={r.id}><b>{r.displayYear}</b><span>{mediumNames[r.medium]} · {r.paperUrl?"Paper":"Answers"}</span><i>→</i></Link>)}</div></section>}{sameYear.length>0&&<section className="related shell sameYear"><h2>{p.displayYear} වෙනත් විෂයන් · {mediumNames[p.medium]}</h2><div className="relatedGrid">{sameYear.map(r=>{const subject=getSubject(r.subject);return <Link href={paperPath(r)} key={r.id}><b>{subject?.si}</b><span>{r.paperUrl&&r.markingSchemeUrl?"Paper + Answers":r.paperUrl?"Paper":"Answers"}</span><i>→</i></Link>})}</div></section>}</>;
}
